# Generated by Django 4.1.2 on 2023-03-26 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MyApp", "0004_talk_rename_like_postlike_rename_read_postread_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postlike",
            options={"verbose_name": "いいね", "verbose_name_plural": "いいね一覧"},
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="post_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("AI", "AI"), ("Python", "Python"), ("java", "java")],
                default="AI",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user")},
        ),
    ]
