# Generated by Django 4.1.2 on 2023-03-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0006_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
