# Generated by Django 4.1.2 on 2023-03-29 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MyApp", "0007_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="talk_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("なし", "なし"),
                    ("AI", "AI"),
                    ("Python", "Python"),
                    ("java", "java"),
                ],
                default="なし",
                max_length=20,
            ),
        ),
    ]
