# Generated by Django 4.1.2 on 2023-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0010_rename_image_post_image1_post_image2_post_image3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image1",
            new_name="image",
        ),
    ]
