# Generated by Django 4.1.2 on 2023-04-02 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MyApp", "0011_rename_image1_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="icons/default_icon.jpg",
                        null=True,
                        upload_to="icons/",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("university", models.CharField(blank=True, max_length=50, null=True)),
                ("sns_account", models.CharField(blank=True, max_length=50, null=True)),
                ("hobby", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "posts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_posts",
                        to="MyApp.post",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "プロフィール",
                "verbose_name_plural": "プロフィール一覧",
            },
        ),
    ]
