# Generated by Django 4.1.2 on 2023-04-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0012_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
