# Generated by Django 4.1.2 on 2023-04-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0013_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="posts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_posts",
                to="MyApp.post",
            ),
        ),
    ]
