# Generated by Django 4.1.2 on 2023-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0015_alter_profile_bio_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("男", "男"), ("女", "女"), ("その他", "その他")],
                max_length=4,
                null=True,
            ),
        ),
    ]
